### ISSUE TITLE
Framework 4.8 and NET 7

### ISSUE THREAD

**Issue by Denifia** [AArnott/MessagePackDualVersions#4]
Are you interested in a PR to demonstrate Framework 4.8 and NET 7 both working with 1.x and 2.x message pack?

**Comment by AArnott** [comment]
Sure. I suspect .NET Framework 4.8 wouldn't be any different than 4.7.2, right? But a demo that uses ALCs on .NET 7 sounds certainly unique and potentially useful for folks. Thank you.

**Comment by Denifia** [comment]
Let me know if you need anything else from me on this one. 

I see you've assigned it to me but I'm not sure what responsibilities that comes with :)

**Comment by AArnott** [comment]
Oh, just that you would create the PR, which you've done. I'll review it now.

**Comment by AArnott** [comment]
Thank you for your contribution.
